[versions]
agp = "8.13.2"
android-compileSdk = "36"
android-minSdk = "24"
android-targetSdk = "36"
androidx-activity = "1.12.2"
androidx-browser = "1.9.0"
androidx-core-ktx = "1.17.0"
androidx-compose-material3-adaptiveNavigationSuite = "1.4.0"
androidx-constraintLayout-compose = "1.1.1"
androidx-lifecycle = "2.10.0"
androidx-room = "2.8.4"
androidx-startup = "1.2.0"
androidx-work = "2.11.0"
buildkonfig = "+"
coil = "3.3.0"
compose = "1.10.0"
compose-material3 = "1.10.0-alpha05"
decompose = "3.4.0"
essenty = "2.5.0"
jetbrains-lifecycle = "2.9.6"
kermit = "2.0.8"
kotlin = "2.3.0"
kotlinx-coroutines = "1.10.2"
kotlinx-datetime = "0.7.1"
kotlinx-serialization = "1.9.0"
ksp = "2.3.4"
ktor = "3.3.3"
ktorfit = "2.7.2"
material-icons = "1.7.3"
material-kolor = "4.1.0"
moko-resources = "0.25.2"
paging = "3.3.6"
skie = "0.10.9"
sqlite = "2.6.2"

[libraries]
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "androidx-activity" }
androidx-browser = { module = "androidx.browser:browser", version.ref = "androidx-browser" }
androidx-core-ktx = { module = "androidx.core:core-ktx", version.ref = "androidx-core-ktx" }
androidx-compose-material3-adaptiveNavigationSuite = { module = "androidx.compose.material3:material3-adaptive-navigation-suite", version.ref = "androidx-compose-material3-adaptiveNavigationSuite" }
androidx-constraintLayout-compose = { module = "androidx.constraintlayout:constraintlayout-compose", version.ref = "androidx-constraintLayout-compose" }
androidx-lifecycle-process = { module = "androidx.lifecycle:lifecycle-process", version.ref = "androidx-lifecycle" }
androidx-paging-compose = { module = "androidx.paging:paging-compose", version.ref = "paging" }
androidx-room-compiler = { module = "androidx.room:room-compiler", version.ref = "androidx-room" }
androidx-room-ktx = { module = "androidx.room:room-ktx", version.ref = "androidx-room" }
androidx-startup-runtime = { module = "androidx.startup:startup-runtime", version.ref = "androidx-startup" }
androidx-work-runtime-ktx = { module = "androidx.work:work-runtime-ktx", version.ref = "androidx-work" }

android-kotlinx-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "kotlinx-coroutines" }
android-ktor-client-android = { module = "io.ktor:ktor-client-android", version.ref = "ktor" }

common-coil-compose = { module = "io.coil-kt.coil3:coil-compose", version.ref = "coil" }
common-coil-network-ktor3 = { module = "io.coil-kt.coil3:coil-network-ktor3", version.ref = "coil" }
common-compose-components-resources = { module = "org.jetbrains.compose.components:components-resources", version.ref = "compose" }
common-compose-foundation = { module = "org.jetbrains.compose.foundation:foundation", version.ref = "compose" }
common-compose-material-icons-core = { module = "org.jetbrains.compose.material:material-icons-core", version.ref = "material-icons" }
common-compose-material-icons-extended = { module = "org.jetbrains.compose.material:material-icons-extended", version.ref = "material-icons" }
common-compose-material3 = { module = "org.jetbrains.compose.material3:material3", version.ref = "compose-material3" }
common-compose-runtime = { module = "org.jetbrains.compose.runtime:runtime", version.ref = "compose" }
common-compose-ui = { module = "org.jetbrains.compose.ui:ui", version.ref = "compose" }
common-compose-ui-tooling = { module = "org.jetbrains.compose.ui:ui-tooling", version.ref = "compose" }
common-compose-ui-tooling-preview = { module = "org.jetbrains.compose.ui:ui-tooling-preview", version.ref = "compose" }
common-decompose = { module = "com.arkivanov.decompose:decompose", version.ref = "decompose" }
common-decompose-extensions-compose = { group = "com.arkivanov.decompose", name = "extensions-compose", version.ref = "decompose" }
common-decompose-extensions-compose-experimental = { group = "com.arkivanov.decompose", name = "extensions-compose-experimental", version.ref = "decompose" }
common-essenty-backHandler = { group = "com.arkivanov.essenty", name = "back-handler", version.ref = "essenty" }
common-essenty-lifecycle = { module = "com.arkivanov.essenty:lifecycle", version.ref = "essenty" }
common-essenty-lifecycle-coroutines = { module = "com.arkivanov.essenty:lifecycle-coroutines", version.ref = "essenty" }
common-essenty-stateKeeper = { group = "com.arkivanov.essenty", name = "state-keeper", version.ref = "essenty" }
common-kermit = { group = "co.touchlab", name = "kermit", version.ref = "kermit" }
common-kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin" }
common-kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinx-coroutines" }
common-kotlinx-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "kotlinx-coroutines" }
common-kotlinx-datetime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version.ref = "kotlinx-datetime" }
common-kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinx-serialization" }
common-ktor-client-contentNegotiation = { module = "io.ktor:ktor-client-content-negotiation", version.ref = "ktor" }
common-ktor-client-core = { module = "io.ktor:ktor-client-core", version.ref = "ktor" }
common-ktor-client-logging = { module = "io.ktor:ktor-client-logging", version.ref = "ktor" }
common-ktor-serialization-kotlinx-json = { module = "io.ktor:ktor-serialization-kotlinx-json", version.ref = "ktor" }
common-ktorfit = { module = "de.jensklingenberg.ktorfit:ktorfit-lib", version.ref = "ktorfit" }
common-lifecycle-runtimeCompose = { module = "org.jetbrains.androidx.lifecycle:lifecycle-runtime-compose", version.ref = "jetbrains-lifecycle" }
common-material-kolor = { module = "com.materialkolor:material-kolor", version.ref = "material-kolor" }
common-moko-resources = { module = "dev.icerock.moko:resources", version.ref = "moko-resources" }
common-moko-resources-compose = { module = "dev.icerock.moko:resources-compose", version.ref = "moko-resources" }
common-paging-common = { module = "androidx.paging:paging-common", version.ref = "paging" }
common-room-paging = { module = "androidx.room:room-paging", version.ref = "androidx-room" }
common-room-runtime = { module = "androidx.room:room-runtime", version.ref = "androidx-room" }
common-sqlite-bundled = { module = "androidx.sqlite:sqlite-bundled", version.ref = "sqlite" }

ios-ktor-client-darwin = { module = "io.ktor:ktor-client-darwin", version.ref = "ktor" }

[plugins]
androidApplication = { id = "com.android.application", version.ref = "agp" }
androidLibrary = { id = "com.android.library", version.ref = "agp" }
buildkonfig = { id = "com.codingfeline.buildkonfig", version.ref = "buildkonfig" }
composeCompiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
composeMultiplatform = { id = "org.jetbrains.compose", version.ref = "compose" }
kotlinKsp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
kotlinMultiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
kotlinSerialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
ktorfit = { id = "de.jensklingenberg.ktorfit", version.ref = "ktorfit" }
moko-resources = { id = "dev.icerock.mobile.multiplatform-resources", version.ref = "moko-resources" }
room = { id = "androidx.room", version.ref = "androidx-room" }
skie = { id = "co.touchlab.skie", version.ref = "skie" }
